### ISSUE TITLE
.mobsf does not apply when path(s) are specified

### ISSUE THREAD

**Issue by mywristbands** [MobSF/mobsfscan#14]
When I run the GitHub Action:
```
    - name: Static Swift code security tests
      uses: MobSF/mobsfscan@main
      with:
        args: '--json'
```
With the .mobsf config file:

```
---
- severity-filter:
  - WARNING
```

It works as expected and only displays results with the severity "WARNING".

However, when I instead specify the path in the args like `args: 'Pods --json'`, it shows results of all severities. Even when specifying other flags in the .mobsf file, they don't work either, so this appears to be an issue with the .mobsf file being ignored altogether when paths are specified.
