### ISSUE TITLE
False positives of android_kotlin_webview_debug

### ISSUE THREAD

**Issue by madlymad** [MobSF/mobsfscan#97]
First of all congrats on your work ❤️  we are using it for a while now and helped us quite a lot!

I would like to report a false positive that I am getting all over my codebase for the `android_kotlin_webview_debug` rule.
I believe that the problem is that `RegexAnd` is not really doing an `and` but an `or` because every place I have the text "WebView" this is reported as a violation 😕 and with the latest changes this report now at least 155 violations.

Violations are reported in imports or in any place the WebView* is identified.

Since this a private repository I cannot share a code link, but I attach some screenshots in case this make more clear the problem

### False positive example of `import`:
![Screenshot 2024-11-05 at 12 54 56 PM](https://github.com/user-attachments/assets/0ac87f6d-80f5-4120-89d8-dbf1f86e5774)

### False positive example of calling the `WebView`Fragment:
![Screenshot 2024-11-05 at 12 13 14 PM](https://github.com/user-attachments/assets/1e51c210-0868-43d3-878f-332911bd4292)

### Only reference of `setWebContentsDebuggingEnabled`
In case it helps this is the only relevant reference of `setWebContentsDebuggingEnabled` in my code that is also flagged with ignore. (Note that tool correctly ignore this specific line!)

![Screenshot 2024-11-05 at 12 21 23 PM](https://github.com/user-attachments/assets/99353679-d3f8-4aad-9f40-f31fd4341806)

Posting here the rule that is triggered:
```
- id: android_kotlin_webview_debug
  message: Remote WebView debugging is enabled.
  type: RegexAnd
  pattern:
    - \.setWebContentsDebuggingEnabled\(true\)
    - WebView
  severity: ERROR
  input_case: exact
```
src: https://github.com/MobSF/mobsfscan/blob/7d67c719fffc8a48accfa3dc33f5dae37c451a02/mobsfscan/rules/patterns/android/kotlin/kotlin_rules.yaml#L100

I remain at your disposal for any further clarification, please let me know if I can do anything else to help in the investigation of this issue, or if there is an explanation why this is triggered and I just have to completely disable this rule.
